### PR TITLE
debug: use Ros wrapper of strnlen(..) instead

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

`strnlen(..)` is not supported by M+ SDK:

> `warning: implicit declaration of function 'strnlen'`

Introduced by #61.

### CODE REVIEW

**Comment by ted-miller** [comment]
Hm. I didn't think to check for build warnings. Just assumed that if it ran/printed correctly that it was ok. 

I will review more closely going forward.

**Review by ted-miller — APPROVED** [review]
